/*
 * generated by Xtext
 */
package com.github.jmodel.validation.plugin;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class ValidationLanguageUiInjectorProvider implements IInjectorProvider {
	
	@Override
	public Injector getInjector() {
		return com.github.jmodel.validation.plugin.ui.internal.ValidationLanguageActivator.getInstance().getInjector("com.github.jmodel.validation.plugin.ValidationLanguage");
	}
	
}
